module: SKTiled
module_version: 0.98
author: Michael Fessenden 
author_url: https://github.com/mfessenden
github_url: https://github.com/mfessenden/SKTiled
github_file_prefix: https://mfessenden.github.io/SKTiled
clean: true
skip_undocumented: true
output: docs/swift
readme: docs/Start.md
#docset_path:
#docset_icon: Swift/Shared/Assets.xcassets/AppIcon.appiconset/Icon.png
#sdk: iphonesimulator
#min_acl: private
skip_undocumented: true
hide_documentation_coverage: true
#head: '<h4><center> SKTiled - SpriteKit</center> </h4>'

exclude:
  - "**/*-ObjC.swift"
  - "Sources/SKTiled+Extensions.swift"

copyright: '© 2016 Michael Fessenden](https://github.com/mfessenden) under [open source license](https://github.com/mfessenden/SKTiled/tree/master/LICENSE).'
    - "-target"
    - "macOS"

copyright: '© 2016 Michael Fessenden](https://github.com/mfessenden) under [open source license](https://github.com/mfessenden/SKTiled/blob/master/LICENSE).'

#swift_version: 3.0

theme: apple

documentation: docs/Tutorial/*.md
abstract: docs/Sections/*.md

custom_categories:
  - name: Tutorial    # references the section page
    children:
      - Getting Started
      - Tiles
      - Coordinates
      - Objects
      - Properties
      - GameplayKit
      - Debugging

  - name: Protocols
    children:
    - SKTiledObject
    - SKTiledSceneDelegate

  - name: Data Types
    children:
    - TilemapOrientation
    - SKObjectType

  - name: Class Reference  # references the section page
    children:
    - SKTilemap
    - SKTilemapParser
    - SKTileset
    - SKTilesetData
    - TiledLayerObject
    - SKTileLayer
    - SKObjectGroup
    - SKImageLayer
    - SKTile
    - SKTileObject
    - SKTiledScene
    - SKTiledSceneCamera
